const String kShortString = "Hello logger!";

const String kString =
    "Dart is a descendant of the ALGOL language family, alongside C, Java, C#, JavaScript, and others.The method cascade syntax, which provides a syntactic shortcut for invoking several methods one after another on the same object, is adopted from Smalltalk. Dart's mixins were influenced by Strongtalk and Ruby. Dart makes use of isolates as a concurrency and security unit when structuring applications. The Isolate concept builds upon the Actor model, which is most famously implemented in Erlang. The Mirror API for performing controlled and secure reflection was first proposed in a paper by Gilad Bracha (who was a member of the Dart team) and David Ungar and originally implemented in Self. While writing and debugging an application, Flutter runs in the Dart virtual machine, which features a just-in-time execution engine. This allows for fast compilation times as well as hot reload, with which modifications to source files can be injected into a running application. Flutter extends this further with support for stateful hot reload, where in most cases changes to source code are reflected immediately in the running app without requiring a restart or any loss of state. For better performance, release versions of Flutter apps on all platforms use ahead-of-time (AOT) compilation, except for on the Web where code is transpiled to JavaScript. Flutter inherits Dart's Pub package manager and software repository, which allows users to publish and use custom packages as well as Flutter-specific plugins.";

const List<String> kList = [
  'the',
  'be',
  'and',
  'of',
  'a',
  'in',
  'to',
  'have',
  'it',
  'I',
  'that',
  'for',
  'you',
  'he',
  'with',
  'on',
  'do',
  'say',
  'this',
  'they',
  'at',
  'but',
  'we',
  'his',
  'from',
  'not',
  'by',
  'she',
  'or',
  'as',
  'what',
  'go',
  'their',
  'can',
  'who',
  'get',
  'if',
  'would',
  'her',
  'all',
  'my',
  'make',
  'about',
  'know',
  'will',
  'up',
  'one',
  'time',
  'there',
  'year',
  'so',
  'think',
  'when',
  'which',
  'them',
  'some',
  'me',
  'people',
  'take',
  'out',
  'into',
  'just',
  'see',
  'him',
  'your',
  'come',
  'could',
  'now',
  'than',
  'like',
  'other',
  'how',
  'then',
  'its',
  'our',
  'two',
  'more',
  'these',
  'want',
  'way',
  'look',
  'first',
  'also',
  'new',
  'because',
  'day',
  'use',
  'no',
  'man',
  'find',
  'here',
  'thing',
  'give',
  'many',
  'well',
  'only',
  'those',
  'tell',
  'very',
  'even',
  'back',
  'any',
  'good',
  'woman',
  'through',
  'us',
  'life',
  'child',
  'work',
  'down',
  'may',
  'after',
  'should',
  'call',
  'world',
  'over',
  'school',
  'still',
  'try',
  'last',
  'ask',
  'need',
  'too',
  'feel',
  'three',
  'state',
  'never',
  'become',
  'between',
  'high',
  'really',
  'something',
  'most',
  'another',
  'much',
  'family',
  'own',
  'leave',
  'put',
  'old',
  'while',
  'mean',
  'keep',
  'student',
  'why',
  'let',
  'great',
  'same',
  'big',
  'group',
  'begin',
  'seem',
  'country',
  'help',
  'talk',
  'where',
  'turn',
  'problem',
  'every',
  'start',
  'hand',
  'might',
  'American',
  'show',
  'part',
  'against',
  'place',
  'such',
  'again',
  'few',
  'case',
  'week',
  'company',
  'system',
  'each',
  'right',
  'program',
  'hear',
  'question',
  'during',
  'play',
  'government',
  'run',
  'small',
  'number',
  'off',
  'always',
  'move',
  'night',
  'live',
  'Mr',
  'point',
  'believe',
  'hold',
  'today',
  'bring',
  'happen',
  'next',
  'without',
  'before',
  'large',
  'million',
  'must',
  'home',
  'under',
  'water',
  'room',
  'write',
  'mother',
  'area',
  'national',
  'money',
  'story',
  'young',
  'fact',
  'month',
  'different',
  'lot',
  'study',
  'book',
  'eye',
  'job',
  'word',
  'though',
  'business',
  'issue',
  'side',
  'kind',
  'four',
  'head',
  'far',
  'black',
  'long',
  'both',
  'little',
  'house',
  'yes',
  'since',
  'provide',
  'service',
  'around',
  'friend',
  'important',
  'father',
  'sit',
  'away',
  'until',
  'power',
  'hour',
  'game',
  'often',
  'yet',
  'line',
  'political',
  'end',
  'among',
  'ever',
  'stand',
  'bad',
  'lose',
  'however',
  'member',
  'pay',
  'law',
  'meet',
  'car',
  'city',
  'almost',
  'include',
  'continue',
  'set',
  'later',
  'community',
  'name',
  'five',
  'once',
  'white',
  'least',
  'president',
  'learn',
  'real',
  'change',
  'team',
  'minute',
  'best',
  'several',
  'idea',
  'kid',
  'body',
  'information',
  'nothing',
  'ago',
  'lead',
  'social',
  'understand',
  'whether',
  'watch',
  'together',
  'follow',
  'parent',
  'stop',
  'face',
  'anything',
  'create',
  'public',
  'already',
  'speak',
  'others',
  'read',
  'level',
  'allow',
  'add',
  'office',
  'spend',
  'door',
  'health',
  'person',
  'art',
  'sure',
  'war',
  'history',
  'party',
  'within',
  'grow',
  'result',
  'open',
  'morning',
  'walk',
  'reason',
  'low',
  'win',
  'research',
  'girl',
  'guy',
  'early',
  'food',
  'moment',
  'himself',
  'air',
  'teacher',
  'force',
  'offer',
  'enough',
  'education',
  'across',
  'although',
  'remember'
];

const Map kMap = {
  "web-app": {
    "servlet": [
      {
        "servlet-name": "cofaxCDS",
        "servlet-class": "org.cofax.cds.CDSServlet",
        "init-param": {
          "configGlossary:installationAt": "Philadelphia, PA",
          "configGlossary:adminEmail": "ksm@pobox.com",
          "configGlossary:poweredBy": "Cofax",
          "configGlossary:poweredByIcon": "/images/cofax.gif",
          "configGlossary:staticPath": "/content/static",
          "templateProcessorClass": "org.cofax.WysiwygTemplate",
          "templateLoaderClass": "org.cofax.FilesTemplateLoader",
          "templatePath": "templates",
          "templateOverridePath": "",
          "defaultListTemplate": "listTemplate.htm",
          "defaultFileTemplate": "articleTemplate.htm",
          "useJSP": false,
          "jspListTemplate": "listTemplate.jsp",
          "jspFileTemplate": "articleTemplate.jsp",
          "cachePackageTagsTrack": 200,
          "cachePackageTagsStore": 200,
          "cachePackageTagsRefresh": 60,
          "cacheTemplatesTrack": 100,
          "cacheTemplatesStore": 50,
          "cacheTemplatesRefresh": 15,
          "cachePagesTrack": 200,
          "cachePagesStore": 100,
          "cachePagesRefresh": 10,
          "cachePagesDirtyRead": 10,
          "searchEngineListTemplate": "forSearchEnginesList.htm",
          "searchEngineFileTemplate": "forSearchEngines.htm",
          "searchEngineRobotsDb": "WEB-INF/robots.db",
          "useDataStore": true,
          "dataStoreClass": "org.cofax.SqlDataStore",
          "redirectionClass": "org.cofax.SqlRedirection",
          "dataStoreName": "cofax",
          "dataStoreDriver": "com.microsoft.jdbc.sqlserver.SQLServerDriver",
          "dataStoreUrl":
              "jdbc:microsoft:sqlserver://LOCALHOST:1433;DatabaseName=goon",
          "dataStoreUser": "sa",
          "dataStorePassword": "dataStoreTestQuery",
          "dataStoreTestQuery": "SET NOCOUNT ON;select test='test';",
          "dataStoreLogFile": "/usr/local/tomcat/logs/datastore.log",
          "dataStoreInitConns": 10,
          "dataStoreMaxConns": 100,
          "dataStoreConnUsageLimit": 100,
          "dataStoreLogLevel": "debug",
          "maxUrlLength": 500
        }
      },
      {
        "servlet-name": "cofaxEmail",
        "servlet-class": "org.cofax.cds.EmailServlet",
        "init-param": {"mailHost": "mail1", "mailHostOverride": "mail2"}
      },
      {
        "servlet-name": "cofaxAdmin",
        "servlet-class": "org.cofax.cds.AdminServlet"
      },
      {
        "servlet-name": "fileServlet",
        "servlet-class": "org.cofax.cds.FileServlet"
      },
      {
        "servlet-name": "cofaxTools",
        "servlet-class": "org.cofax.cms.CofaxToolsServlet",
        "init-param": {
          "templatePath": "toolstemplates/",
          "log": 1,
          "logLocation": "/usr/local/tomcat/logs/CofaxTools.log",
          "logMaxSize": "",
          "dataLog": 1,
          "dataLogLocation": "/usr/local/tomcat/logs/dataLog.log",
          "dataLogMaxSize": "",
          "removePageCache": "/content/admin/remove?cache=pages&id=",
          "removeTemplateCache": "/content/admin/remove?cache=templates&id=",
          "fileTransferFolder":
              "/usr/local/tomcat/webapps/content/fileTransferFolder",
          "lookInContext": 1,
          "adminGroupID": 4,
          "betaServer": true
        }
      }
    ],
    "servlet-mapping": {
      "cofaxCDS": "/",
      "cofaxEmail": "/cofaxutil/aemail/*",
      "cofaxAdmin": "/admin/*",
      "fileServlet": "/static/*",
      "cofaxTools": "/tools/*"
    },
    "taglib": {
      "taglib-uri": "cofax.tld",
      "taglib-location": "/WEB-INF/tlds/cofax.tld"
    }
  }
};

const Map<String, dynamic> kModelData = {
  "menu": {
    "header": "SVG Viewer",
    "items": [
      {"id": "Open"},
      {"id": "OpenNew", "label": "Open New"},
      null,
      {"id": "ZoomIn", "label": "Zoom In"},
      {"id": "ZoomOut", "label": "Zoom Out"},
      {"id": "OriginalView", "label": "Original View"},
      null,
      {"id": "Quality"},
      {"id": "Pause"},
      {"id": "Mute"},
      null,
      {"id": "Find", "label": "Find..."},
      {"id": "FindAgain", "label": "Find Again"},
      {"id": "Copy"},
      {"id": "CopyAgain", "label": "Copy Again"},
      {"id": "CopySVG", "label": "Copy SVG"},
      {"id": "ViewSVG", "label": "View SVG"},
      {"id": "ViewSource", "label": "View Source"},
      {"id": "SaveAs", "label": "Save As"},
      null,
      {"id": "Help"},
      {"id": "About", "label": "About Adobe CVG Viewer..."}
    ]
  }
};
